#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the catAndMouse function below.
def catAndMouse(x, y, z):
    
    a=abs(int(z)-int(x))
    b=abs(int(z)-int(y))
    
    str=""
    if a>b:
        str="Cat B"
    elif a<b:
        str="Cat A"
    else:
        str="Mouse C"
    #print(a)
    return str

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input())

    for q_itr in range(q):
        xyz = input().split()

        x = int(xyz[0])

        y = int(xyz[1])

        z = int(xyz[2])

        result = catAndMouse(x, y, z)

        fptr.write(result + '\n')

    fptr.close()
