#!/bin/python3

import math
import os
import random
import re
import sys
from itertools import groupby



if __name__ == '__main__':
    s = input()
    f=set(s)
    h=[]
    dic={}
    for k in f:
        i=list(s).count(k)
        #l=len(i)
        dic.update({k:i})
    sort_dic=dict(sorted(dic.items(),key=lambda item: item[0]))
    dd=dict(sorted(sort_dic.items(),key=lambda item: item[1],reverse=True))
    for i in range(3):
        print(f"{list(dd.keys())[i]} {list(dd.values())[i]}")
