#!/bin/python3

import math
import os
import random
import re
import sys
from collections import Counter 
import itertools 

#
# Complete the 'formingMagicSquare' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY s as parameter.
#

def formingMagicSquare(s):
    # Write your code here
    z=[]
    k=[]
    h=[]
    result=0
    for i in range(len(s)):
        for j in range(len(s)):
            k.append(s[i][j])
    
       d=(1,2,3,4,5,6,7,8,9)
    r=tuple(itertools.permutations(d,9))
    f=len(r)
    for i in range(f):
        if sum(r[i][0:3])==15 and sum(r[i][3:6])==15 and sum(r[i][6:9])==15 and r[i][0]+r[i][4]+r[i][8]==15 and r[i][2]+r[i][4]+r[i][6]==15 and r[i][4]==5 and r[i][1]%2!=0 and r[i][3]%2!=0 and r[i][5]%2!=0 and r[i][7]%2!=0 and r[i][0]+r[i][3]+r[i][6]==15 and r[i][1]+r[i][4]+r[i][7]==15 and r[i][2]+r[i][5]+r[i][8]==15:
            z.append(r[i])
    print(z)
    v=len(z)
    d={}
    for i in range(v):
        result=tuple(a-b for a,b in zip(k,z[i]) )
        postr=tuple(abs(x) for x in result)
        h.append(sum(postr))
    return min(h)
if __name__ =="__main__":
    fptr = open(os.environ['OUTPUT_PATH'], 'w')#

    s = []

    for _ in range(3):
        s.append(list(map(int, input().rstrip().split())))

    result = formingMagicSquare(s)

    fptr.write(str(result) + '\n')

    fptr.close()

