#!/bin/python3

import math
import os
import random
import re
import sys




first_multiple_input = input().rstrip().split()

n = int(first_multiple_input[0])

m = int(first_multiple_input[1])

matrix = []

for _ in range(n):
    matrix_item = input()
    
    matrix.append(matrix_item)
    
decode_matrix=[]
for col in range(m):
    for row in range(n):
        decode_matrix.append(matrix[row][col])
l="".join(decode_matrix)
h=re.compile(r"\b[ !@#$%&]+\b",re.M)
output=re.sub(h,' ',l)
print(output)
