#!/bin/python3

import math
import os
import random
import re
import sys
from datetime import datetime



# Complete the time_delta function below.
def time_delta(t1, t2):
    #now=datetime.now()
    fmt="%a %d %b %Y %H:%M:%S %z"
    t1_=datetime.strptime(t1,fmt)
    t2_=datetime.strptime(t2,fmt)
    
    #date_=datetime.strftime(now,fmt)
    #today = datetime(datetime.astimezone.utc)
    t_z=t1_-t2_
    
    
    u=str(int(t_z.total_seconds()))
    if int(u)<0:
        k=-int(u) 
        return str(k)
    else:
        return u 

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())
    #print(t)

    for t_itr in range(t):
        t1 = input()

        t2 = input()

        delta = time_delta(t1, t2)

        fptr.write(delta+'\n')

    fptr.close()
